### PR TITLE
Split the 'Distributive' class to generalise it's kind and allow instances that require 'Traversable'

### PR DESCRIPTION
**Pull request by clintonmead**
This pull request is bit less innocuous that the last one. But I'll try to walk you through it.

For my datatype, I can almost implement `distribute`. Here's the signature of `distribute`:

`distribute :: Rank1.Functor f1 => f1 (g f2) -> g (Compose f1 f2)`

But there's two problems:

1. `distributeM :: Rank1.Monad f => f (g f) -> g f` forces kind `(* -> *) -> *` but my type is of kind `(k -> *) -> *`.
2. My datatype is similar to a Rank-2 version of [what's in this StackOverflow question](https://stackoverflow.com/questions/45025898/pushing-a-functor-into-a-tuple/45026684#45026684), just like the answer to that question suggests, I need the argument to `distributeWith` to be `Traversable`, not just a `Functor`. 

So to solve point 1, I've moved `distributeM` into a new class `DistributiveM`, which has `Distributive` as a superclass, and defined the appropriate instances. Now the kind of `Distributive` is more general.

To solve point 2, I've created a class `DistributiveTraversable`, that has all the functions of `Distributive`, but with a `Traversable` constraint. `DistributiveTraversable` is now made a superclass of `Distributive`, as if you've got an implementation of `Distributive` you have a implementation of `DistributiveTraversable`, as every `Functor` is a `Traversable`. Indeed, I've defined a default methods that allow an empty instance declaration for `DistributiveTraversable` if `Distributive` is defined. 

I've bumped the version number to 0.2 as this is not a backward compatible change. Code that just calls the functions will be fine as they all have the same names as previously, but instances will have to be added for the two new classes. The upgrade path involves the following for each existing instance:

1. Writing an empty instance for `DistributiveTraversable`. 
2. Creating an instance for `DistributiveM`.
3. Moving the definition of `distributeM` from `Distributive` to `DistributiveM`.

I understand if you're not a fan of this as it breaks backwards compatibility and complicates things a bit, so if you don't want to integrate something like this just say and I'll fork my version off.

### CODE REVIEW

**Comment by blamario** [comment]
I wouldn't worry too much about the backward compatibilty yet, the library is still fresh and experimental.

I can accept the need for DistributiveTraversable superclass. I also agree with taking the distributeM method out of Distributive, but I'm not convinced it needs to be put in a new subclass. I'd prefer it as a standalone method with the fixed definition `distributeM = distributeWith Rank1.join`, unless you have a convincing example of a superior instance method implementation.

Finally, before I accept your pull request, can you please add the missing code to the Rank2.TH module to generate the `DistributiveTraversable` instances?

**Comment by clintonmead** [comment]
As you mentioned, made `distributeM` a plain function, removing the `DistributiveM` class.

I think I've added the template Haskell code to generate the instances for the `DistributiveTraversable` class, but I haven't tested it as I'm not using `Rank2.TH` myself. You should probably check what I'm doing is sensible.

**Comment by clintonmead** [comment]
Also some utility functions I found useful regarding lifting over traversables.

**Comment by blamario** [comment]
Looks good.

**Pull request merged**
